language: java
jdk: oraclejdk8
sudo: required
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: MGNvDqKLrLWSLfMFPOI3VDJ+22MsX1qJz4KPt5L5fhMVkUTo8QAz/sIUHN3t0bOYUkv9iDkWhM7NaYPrkxdEjYBjnmOloO/VQhMz2c5HPc66SfmLui9Jbh3Vg05wsTyJKcJvwonxIH+7pFNFgeay9DMk3MqzIVxrcvOAPXhy6pqzl1ZCwHdNIU7g+N3qvcbLTDQjtZ7ZIXylS7NLxEi/6ZSfuudigO6j+AZkig1gk+4TCEPotCqFoMySpP6wN3WTEZB2yY/evJE4F3b2mWsxJ/ARBOkAiCA7to+XlVFmfsAysg61GI/Pq5/DpmzeY42yniFAq3lzd+P498TditsiEdHtEa0cv71uV5WR1M4CvRtlw6gUhOeKLEF5IPCA+ywBnApfsjePBwViS2PbTbcjp1DwZrsmkTeuwQIlDEsj58XBFX8e9kIozErx7IFksy82zup36H3tcZVNXs+CxMMksOgpl3GrpEjVWLDCxqyrPpIWzx0UyaRVxgYkrqqmpOwiVE+f/TJyeJiGwaQEdIUZSE5hxuGzeFCVgCM4bvJcI5o7zzctWe6WKrCPocJKwemjb00ThQywFk87ZWimEy//B4zfCMqBxQCH4P5kob7Qih67lpEw91VxvfOid/RBP26E6i3yVXTCgrTXhMmE9VTfntKChO9yE1jVUn1YYHhdJ+M=
  - secure: vGxJQ9RM4BS2rFgC0UdNrrZ9xdpIP5pLebQ3p4b+ZvUfod1gbWxaAQWubuJb/i8iHbMHT++iT0OBxa0qbu1Ijwl6vrwHlgvdbKNoeczxZER1ch6Bbmhw0URnvPSWD5aaJNZn0XzzMhiaBjTbRGT0DIPbSmMs7PjpYZfW7wmII3OGaPJkTgHGWE2rqo9m2lw3D8YqOZdmnHTGKGpt6J3aLpARQy5DQGUUPH/zV4w+v6n4+8A0C/vwvTh0IeT9PIMElGAT76nvCsNqsXPuwvpepDoPGHIkRe3NhfGeDq1l8Q/6YLwIHQxkQA5HpbNzpkhhlksSXLsZS4T4XuRoJJA7UKjbap2aBoXdXCUKe1gSL2Z4+pJUgouKzmjMDcALtYITPBEVA08AstIQvVouk0e2DtAxNZFn8ofXkHlijrMjtP/sGRpJkQonaX/h4fDTunp8V0sMzvKH2hGVKhadEVsDTBYEb7I5caHXCD2igvv6snm85qaGehfvUPUbhFOKJV0MprukoUEV7tDabgthmSiznHQH0HBnbiUBwvC/0DILmbGcbgg9CwOL3KTeC58vXFhpmoHHVtr988UFb/OdgG9BnfIDZ2dxswRtpoJwa5iJwOuTeA9Nynq4RmK/rpqvSF1N2lUW0TmbFDwus/62W1KvNn0ErGkP40B7c9a99OqsvyM=
script:
- "./mvnw clean install -B"
cache:
  directories:
  - "$HOME/.m2/repository"
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export IMAGE_NAME=cbonami/shop-gateway
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
