language: java
jdk: oraclejdk8
sudo: required
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - DOCKER_USER="cbonami"
  - secure: QMM/HZh6lqUMi9CBwfbw6utP2J9uoqBGms+gXGmyu/BfWqinWoh30AsTUM7vFYhbnklnI5ETpg9WbdKhLT2cR3jxf+COnvao8NqNRqEm7Bvo2oIgAktZMI8VRtqGs1IYkviQDmoljxdlOqEWp9ctjp1vBEkvLdFOsrnuGE8UkA4CicG+hFl8W9vCSfzmD3QsXxyr9KWwSpZUzTtQKX3rRH7NL/dedPklyjrn0kanUMiDl/Ep6KzCQ64kU2oX3rR5SUzav2NFDPEMk7snkpTXdzoMpxIPCLC1ew06QwjSlVXIWHRoyEPGrJFLF1YbU6iEFG6c53wXIDm9hTJ+B8nrMawSY2rowrOUT07EYB1+1Q1oaW8A7lKbsNJclVTPm70usgmVJaBtQApEQNC3A8/qhLQZ9b2+I9n+VWQ95tNQZDXElz+IV93QuENLSoyt7Pd7KSM0ADew0Lk6ytcvGYhVr02bs4ZZYUirfmrLK3FB78fNXFesZvqIwGDIcZrqQfksxBW6fUYV/nhKZO1ivbppGzCj33nmIuNeuhsPh7VvW1g/2cwPEjIH+AxgXU1uQlnK8JbxPSNtJIk/xMwmur0n/fuJiLDbAS5QietMN+xnd8Zjfc8USusluuW6R4/JhE9XYFx0dxhC7ELmTdAOM/speg9cUdsrjYTXXekCpBkC3jI=
  - secure: iZETX10YlScPFY/EUognY2bpFrv37FfHcFfihei6hTi9mENa7ge6Rqm2+CMDg0feRegKVQ+rXdXKYHgyqVD7ZBLDi+MFo4/4qFHdYXTeB99lqsUAUPdVHRKt5SPc5Ia8SPEsVRpcX8reeiJahBzxhRhl/Ye+OjMD1YpTGmhfgUVWICWEktuyAJGRYTmI1CDiYe4PzGJobgy6C+5Y35mHvOHtdgdIsx08/SrkT+GzvoR0fwi82pnFovBV1UQMUvanjz8yzdgQjDh8sTDbllanPzpTbbAUfL8npdwSNm6U0CVanUJQHPyyGmBkAj/kuBfNQY8voHpnz7fkpWOnElqKqXNws10nJ0ms91Y908PXQESMDzHbgfx5k3Ry26zqhs/2Mz24SDzqVBIwGHgBVy11egiwfCYuGg5crDLE5syA3RRyDBZzz+2cY1V6acdL8SD+u9FMBZb7VH57mhCz5fYdWuUXeUUyBbhRfSJRKhGqRuZCVlzlvhroeEjj5COahCKIPifpxGhn9rR5HfFQLVLjlRQffp6//fxevfqheSC9HJD2gYOBV9dcppVB3v2p/E5xXuTcFLF9ddx5HiIojzn1JWK+1+wCYwwJHGDusDmxm96dTP6tiLjvAJ/nJjIDTVh+rvf185YpWPsJ34m3On1P4l48mCC62uJB9gTg0pexy4U=
before_install:
- chmod +x mvnw
script:
- "./mvnw clean install -B"
cache:
  directories:
  - "$HOME/.m2/repository"
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export IMAGE_NAME=cbonami/shop-gateway
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
