language: java
jdk: oraclejdk8
sudo: required
services:
- docker
env:
  global:
  # DOCKER_USER + DOCKER_PASS
  - secure: "ovSKORa2IOa07z6+f6JnZ1ULZyQ6PxzY+myjNzjXZzclpDd3DRAlTpayo2GmYIi3h8IKEuxxx8JOe+o1ZVI0Gs7PHlvKV9i2Tsvy4QrO7zSJf85EGgNwba5knZT9e2YrEW8+0qdgQ83Ern9y1I96sPCbeqhWdsHlckyJV/q6tR26ZF1HsuFdd39KujczUB24el0ulcnG6eWUlJCOAa7qJyccPJj15xfsYQ1NKv1kQbk5rwx9ELY4WKh4Zon13gx4Qj6mintMNbaIZ09b99Fvhkn3W8/fSHTRTcENQu6XlSYlOMymkPyOonPL1qjhlpB9ehpUwJQ85aSQsEP8iRt+g7yDOoFrt81z8uzxfogj8ToS6Ius57YRGa2Yu0iTZbN6gpERlCdr2YXfiWqCtxdHGaJ7AIegqpIfwFWYCWxNDoJmgsvNkAcSahjmgwFXkhvYqhxT0NB1uNcS/V4T0T4ojgzdm8ud++MH4UvGyIOaSJUryDF9BK6jRj77V5hVKFd8PlhhssPqg1/corARxr2jUyiAP2/AelnicsdYv2IOM7XF/YBoz+MgHHec6tgLn0E2ia5YHq1AcjNecRM/T7K9MTUya8NuywmB9Ddwtl93ITa35z7dsgxTNK4Sbk/zbKeMbo/JGTOdyflme/CUcgWWPCsFvh0o7TwN5SvsAeKPM2Q="
  - secure: "svyEDvluTtNvG9qd9f6FiraYanItkGuTP7BGLwbe36mpJiJuaGWcj5z45+8x5gQ7mpRx82p1+AJ5X7xYxOtAWMd2mRoJ75kZ8FiDFbaXk43uW4RM8NhSFSpLUYtH1ZmqSmXde59Ys8X+z2IPg7QYTPy4hOAHe6NRnmGeOmi+rpmPoa1+y3qCLpH3ZWaGtt3+G+UbbNQXHXk40i2tsVtgo77vDOHeislSiCNiucq4Gw5HAkF/j1SLAVJ1+0hcVXh5CXCAvXawj49hCO53q/ncLBrXeNGrtwJ8Dpovytobsp7nENa4k0ZRwctUYF5A8iWfwgC7PYSgvPJ0mdakPAou93zA7nk/6pE5UpqZkprqNKvCwYPHMbQeIOIMiA9Z/guwcIKIu7W5RwEczQh7I1oWA5SSfblMDLFS5I1AkGUtQdQxhOro4jOy5zZGHBj/kPgVJ/GaHcqziS9pGF9z4CF+/LbxJjI+id7HXbQbI/ZN99nGSzq/ZqfJry89TGbpoD5KY6cTocZVL1EKe4QPN7lPMso2fjhasgmTgzPJpsXLVNDSyDe/Mql3qWl/3K+O0AmpKl3h9bWYqwTHbNf/FAwjOl5OVVoxKcmtUTrNfQtzCP8SytSAF50dEQcxusgbT/7zcOzO0uv8eRR3eFzjcEhlBEMyzQOnEBVsUNKmaOs+3xk="
  - COMMIT=${TRAVIS_COMMIT::7}
script:
- "./mvnw clean install -B"
cache:
  directories:
  - "$HOME/.m2/repository"
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export IMAGE_NAME=cbonami/shop-gateway
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
