language: java
jdk: oraclejdk8
sudo: required
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: bo/k3W6ybEdp8wUK0G0CUKR071MVvnCAkK8wwpf30Z2NC0Ctwk7+tFpDjNtpZOQMM+yXppFptw7cb79dqVVruvq7y1wDbe7o7riRtV5IVOcixVuwPuTHV53InZo9p+F2SM0GealagdKHIfolYstWjoJI/F4xXcrjaQTTOQLeBM28YdlZU9+yHD4pSTKne06FnBYVVtTglXGcN+gMWYPXHV9l3Hr7bPeIL/kYC8uQ0K9Zrc3A7o4IblBNe6qjGbrt/30WUO+QvoOrHV0wGszAPCM7nqX7qv2on4G3qnb1n1fSjWxwQ+cev5wp/UA48irM5G1Z35iHZ3P8VI2+BYCVOoMW+hLTVCbMNGdxf4JBA+iOXJMBY+pujvZlp6Ytz3XhIw7mvGoYZIB61u0hUvENPWv4lwfa3czoECpTesHiqd9MNDSLjkEmMW5dnYjxI5+KgSYJJ+Ma4QgEEmSQgcKyQpoJRNFsuEACxBW84tU8X84l+I7UQjdqkIP6JjHXPoaaj8muAEHrltENVAFmtBMmowgIhazcLV/0jN1P9jtR+HcBRAwPTktm0uHidbShLdrehHEVUzj6btBZEy0eVHFOhfr53+Eior+dLkYmzA+BJdC5Y1P6kU6+GzgdH8c3LSYRYSjmuOKwzhhEruMuUhtrzPSZxAHXkd+bgzVY8pNTbis=
  - secure: mwjapSwFDlFA/tz3IYBiZ+4sBuRP0oa4IBVhZpW975ooM5eOWfQ02j4F8PNjWB8vcYE61k18sZPt3+oTdy3TH7mE/3SdzAgHjInTNwOOxeiM1xo9WbjKi0vgOv6jSSdQ6r4n9DnPNyVMohmB6hlROiI9XCaOsMUx4rlzgEoezu0aDaCcTmmEf4ow7kvaNAXMzX1Q5o060qJ8DdAZYYwreAeUkiU3HO0qvlKkevOv+6EwuH+EtJQ5EW1EqkhEmGlll05cxhQdrL1nqCiDg/1VHNoLK6OxuEH3X+mWmmihvo0DWJ4Nx9wpr81KrydU1zE3Eg2FdeOuwbDhLsX14PbmTkjxPNMwtQBr3U/E6Tnq/CeOWCai7G8/IimL9yNOw7UtpLQyHm3Re1seFol8jv1ga6132a3nnVzOsOoMh0xLyuqiD6dG0MsBSqAgnINk8w4lxrVv/52AqQzR5qqPVkiBhvvHGW6on3xphLaPLY9i+dpuAO5x6ZBY6Al4xAKmxTE8lmZL4rEaaDp1BTVhYzy1csCdxVs/5YUCD0ICCqrirUeo6u/ttPwlEEWqo9Ew3N7WpY7J9IfwQwOFn8es/iGyXfBxcnUyS1qZ6tF5c4pY2KGCRpJQCafV3KBL71xfHTyXVOG6x7IJKm+vsY9L1kzJliHXj1hxWS2b+gRolSzODXw=
before_install:
- chmod +x mvnw
script:
- "./mvnw clean install -B"
cache:
  directories:
  - "$HOME/.m2/repository"
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export IMAGE_NAME=cbonami/shop-gateway
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
