server:
  port: 8080
spring:
  application:
    name: shop-gateway
  security:
    user:
      name: actuator
      password: actuator
      roles: ACTUATOR_ADMIN
  cloud:
    gateway:
      routes:
      - id: productcatalogue
        predicates:
        - Path=/productcatalogue/**
        filters:
        - RewritePath=/productcatalogue/(?<segment>.*), /$\{segment}
        uri: http://productcatalogue:8080
      - id: stockmanager
        predicates:
        - Path=/stockmanager/**
        filters:
        - RewritePath=/stockmanager/(?<segment>.*), /$\{segment}
        uri: http://stockmanager:8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

#logging:
#  file: app.log